NAME = SPOTCE
ICON = icon.png
DESCRIPTION = "Spotify controller for TI-84 Plus CE"
COMPRESSED = YES
ARCHIVED = YES

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

include $(CEDEV)/meta/makefile.mk
